name: OCR Batch with Tesseract

on:
  workflow_dispatch:

jobs:
  ocr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-por poppler-utils qpdf

      - name: Run OCR on input files (images + PDFs)
        run: |
          mkdir -p output/txt
          mkdir -p output/pdf
          mkdir -p tmp

          for f in $(ls input/* | sort); do
            base=$(basename "$f")
            name="${base%.*}"

            if [[ "$f" == *.pdf ]]; then
              # converte PDF em imagens (uma por página)
              pdftoppm -r 300 "$f" "tmp/${name}" -png
              for img in tmp/${name}-*.png; do
                page=$(basename "$img" .png)
                # gera TXT
                tesseract "$img" "output/txt/$page" -l por
                # gera PDF pesquisável
                tesseract "$img" "output/pdf/$page" -l por pdf
              done
            else
              # é imagem direta
              tesseract "$f" "output/txt/$name" -l por
              tesseract "$f" "output/pdf/$name" -l por pdf
            fi
          done

      - name: Merge PDFs in sequence
        run: |
          mkdir -p output/final
          qpdf --empty --pages output/pdf/*.pdf -- output/final/merged.pdf

      - name: Merge TXT in sequence
        run: |
          cat output/txt/*.txt > output/final/merged.txt

      - name: Upload OCR results
        uses: actions/upload-artifact@v4
        with:
          name: ocr-results
          path: output/
